[project]
name = "GAIA"
version = "0.1.0"
description = "Exoplanet classification system with an explainable ANN model"
authors = [{ name = "Krzysztof Gonet", email = "36476874+Savaed@users.noreply.github.com" }]
readme = "README.md"
dependencies = [
    "structlog"
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
