defaults:
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

data:
  cadence: LONG
  root_dir: gs://gaia-data-kepler
  time_series_dir: ${data.root_dir}/raw/time_series
  tables_dir: ${data.root_dir}/raw/tables
  tce_filename: ${data.tables_dir}/q1_q17_dr25_tce.csv

  fetch:
    num_parallel_requests: 50
    processed_urls_filename: ${data.time_series_dir}/processed_urls_llc.txt
    mast_base_url: https://mast.stsci.edu/api/v0.1/Download/file
    nasa_urls:
      - https://exoplanetarchive.ipac.caltech.edu/cgi-bin/nstedAPI/nph-nstedAPI?table=q1_q17_dr25_tce&format=csv&select=kepid,tce_plnt_num,tce_rogue_flag,tce_period,tce_time0bk,tce_time0,tce_duration,tce_depth,tce_prad,tcet_period,boot_fap,tce_cap_stat,tce_hap_stat,tce_rb_tcount0,tce_maxmesd
      - https://exoplanetarchive.ipac.caltech.edu/cgi-bin/nstedAPI/nph-nstedAPI?table=q1_q17_dr25_stellar&format=csv&select=kepid,teff,radius,mass,dens,logg,feh
      - https://exoplanetarchive.ipac.caltech.edu/cgi-bin/nstedAPI/nph-nstedAPI?table=q1_q17_dr25_koi&format=csv&select=kepid,kepoi_name,kepler_name,koi_disposition,koi_pdisposition,koi_tce_plnt_num
