defaults:
  - _self_

  - data: kepler_local
  - data_providers: kepler_local
  - download: kepler
  - preprocess_data: kepler
  - ui: local
  - create_features: kepler_local

  - override hydra/job_logging: none
  - override hydra/hydra_logging: none
