defaults:
  - override hydra/job_logging: none
  - override hydra/hydra_logging: none

mission: KEPLER
data:
  raw_tables_dir: data/raw/tables
  raw_time_series_dir: /mnt/d/time_series
  interim_tables_dir: data/interim/tables
  interim_time_series_dir: data/interim/time_series

  load:
    skip_tables: yes
    observation_cadence: llc # Long ~30min
    tce_file: ${data.raw_tables_dir}/q1_q17_dr25_tce.csv
    target_id_column: kepid
    verbose: yes
    api:
      mast_base_url: https://mast.stsci.edu/api/v0.1/Download/file?uri=mast:Kepler/url/missions/kepler/lightcurves
      nasa_base_url: https://exoplanetarchive.ipac.caltech.edu/cgi-bin/nstedAPI/nph-nstedAPI
      num_async_requests: 25
      requests:
        - - ${data.load.api.nasa_base_url}?table=q1_q17_dr25_tce&columns=kepid,tce_plnt_num,tce_rogue_flag,tce_period,tce_time0bk,tce_time0,tce_duration,tce_depth,tce_prad,tcet_period,boot_fap,tce_cap_stat,tce_hap_stat,tce_rb_tcount0&format=csv
          - q1_q17_dr25_tce.csv
        - - ${data.load.api.nasa_base_url}?table=q1_q17_dr25_koi&columns=kepid,kepoi_name,kepler_name,koi_disposition,koi_pdisposition,koi_tce_plnt_num&format=csv
          - q1_q17_dr25_koi.csv
        - - ${data.load.api.nasa_base_url}?table=q1_q17_dr25_stellar&columns=kepid,teff,radius,mass,dens,logg,feh&format=csv
          - q1_q17_dr25_stellar.csv

  store:
    tce:
      reader: parquet
      source: ${data.interim_tables_dir}/q1_q17_dr25_tce_merged.parquet
      mapper: dfg
      params_schema:
        target_id: kepid
        tce_id: tce_plnt_num
        name: kepler_name
        label: label
        duration: tce_duration
        epoch: tce_time0bk
        period: tce_period

    stellar:
      reader: parquet
      source: ${data.interim_tables_dir}/q1_q17_dr25_stellar.parquet
      mapper: dfg
      params_schema:
        id: kepid

    time_series:
      reader: parquet
      source: ${data.interim_time_series_dir}

  tce_merge:
    select_sql: SELECT tce.* REPLACE (tce_duration / 24 AS tce_duration), koi.* EXCLUDE(kepid), koi.kepid AS kepid_koi # Mark TCEs whose are not present in KOI and convert 'duration' from hours to days
    join_sql: "'${data.raw_tables_dir}/${data.load.api.requests[0][1]}' tce LEFT JOIN '${data.raw_tables_dir}/${data.load.api.requests[1][1]}' koi ON tce.kepid=koi.kepid AND tce.tce_plnt_num=koi.koi_tce_plnt_num LEFT JOIN '${data.raw_tables_dir}/cfp.csv' cfp ON koi.kepoi_name=cfp.kepoi_name WHERE tce.tce_rogue_flag=0"
    label_conditions_case_sql:
      - WHEN koi.koi_disposition='CONFIRMED' THEN 'PC'
      - WHEN cfp.fpwg_disp_status='CERTIFIED FP' THEN 'AFP'
      - WHEN cfp.fpwg_disp_status='CERTIFIED FA' OR kepid_koi IS NULL THEN 'NTP'
      - ELSE 'UNKNOWN'
    output_file: ${data.interim_tables_dir}/q1_q17_dr25_tce_merged.csv

  convert:
    tce:
      inputs: ${data.interim_tables_dir}/q1_q17_dr25_tce_merged.csv
      output: ${data.interim_tables_dir}/q1_q17_dr25_tce.parquet
      columns:
        - kepid
        - tce_plnt_num
        - tce_cap_stat
        - tce_hap_stat
        - boot_fap
        - tce_rb_tcount0
        - tce_prad
        - tcet_period
        - tce_depth
        - tce_time0bk
        - tce_duration
        - tce_period
        - kepler_name
        - label_text
      columns_map:
        kepid: target_id
        tce_plnt_num: id
        tce_cap_stat: opt_ghost_core_aperture_corr
        tce_hap_stat: opt_ghost_halo_aperture_corr
        boot_fap: bootstrap_false_alarm_proba
        tce_rb_tcount0: rolling_band_fgt
        tce_prad: radius
        tcet_period: fitted_period
        tce_depth: transit_depth
        tce_time0bk: epoch
        tce_duration: duration
        tce_period: period
        kepler_name: name

    stellar:
      inputs: ${data.raw_tables_dir}/q1_q17_dr25_stellar.csv
      output: ${data.interim_tables_dir}/q1_q17_dr25_stellar.parquet
      columns:
        - kepid
        - teff
        - radius
        - mass
        - dens
        - logg
        - feh
      columns_map:
        kepid: id
        teff: effective_temperature
        dens: density
        logg: surface_gravity
        feh: metallicity

    time_series:
      inputs: ${data.raw_time_series_dir}/*.fits
      output: ${data.interim_time_series_dir}
      data_header: LIGHTCURVE
      data_columns: [TIME, PDCSAP_FLUX, MOM_CENTR1, MOM_CENTR2]
      meta_columns: [KEPLERID, QUARTER]
      path_target_id_pattern: (?<=kplr)\d{9}
      names_map:
        TIME: time
        PDCSAP_FLUX: pdcsap_flux
        MOM_CENTR1: mom_centr1
        MOM_CENTR2: mom_centr2
        KEPLERID: id
        QUARTER: period

ui:
  assets_dir: gaia/ui/assets
  external_stylesheets:
    - https://use.fontawesome.com/releases/v6.4.0/css/all.css
    - https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700;800&display=swap
  available_graphs:
    pdcsap_flux: pdcsap_flux
    centroid_shift: mom_centr1,mom_centr2
  tce_filepath: ${data.interim_tables_dir}/q1_q17_dr25_tce.parquet
  stellar_parameters_filepath: ${data.interim_tables_dir}/q1_q17_dr25_stellar.parquet
  time_series_dir: ${data.interim_time_series_dir}
  server_params:
    debug: true
    host: 127.0.0.1
    port: 8050
    dev_tools_hot_reload: true
