name: main

on:
  push:
    branches: [main]
  pull_request:

env:
  FORCE_COLOR: "1"
  TOX_TESTENV_PASSENV: FORCE_COLOR
  MYPY_FORCE_COLOR: "1"

jobs:
  main:
    name: Main workflow
    strategy:
      matrix:
        os: [ubuntu-20.04]
        python-version: ["3.10"]
      fail-fast: false
    defaults:
      run:
        shell: bash
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.0

      - name: Install tox
        run: python -m pip --disable-pip-version-check install tox virtualenv

      - name: Run test via tox
        run: tox -e py

      - name: Run Codecov report
        uses: codecov/codecov-action@v3
        with:
          # see https://github.com/codecov/codecov-action/issues/557 - for private repos only
          token: ${{ secrets.CODECOV_TOKEN }}
          file: coverage.xml
