name: tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tests:
    name: ${{ matrix.os }} / python-${{ matrix.python-version }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
        python-version: ["3.9"]
      fail-fast: false
    defaults:
      run:
        shell: bash
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set up environment
        uses: ./.github/actions/setup-poetry-env

      - name: Run pytest
        run: poetry run pytest tests
      
      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v3
        with:
          # see https://github.com/codecov/codecov-action/issues/557
          token: ${{ secrets.CODECOV_TOKEN }}

                